[package]
name = "phex"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
env_logger = "0.11.8"
log = "0.4.27"
pollster = "0.4.0"
rand = "0.9.1"
wgpu = "26.0.1"
winit = "0.30.11"
